/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjpoobrenocaiojoao.view;

/**
 *
 * @author mumei
 */
public class Vendedor extends javax.swing.JFrame {

    /**
     * Creates new form Vendedor
     */
    public Vendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbVendedorCPF = new javax.swing.JLabel();
        lbVendedorNome = new javax.swing.JLabel();
        lbVendedorEnde = new javax.swing.JLabel();
        lbVendedorCidade = new javax.swing.JLabel();
        lbVendedorCEP = new javax.swing.JLabel();
        txtVendedorNome = new javax.swing.JTextField();
        txtVendedorEndereco = new javax.swing.JTextField();
        txtVendedorCidade = new javax.swing.JTextField();
        txtVendedorCEP = new javax.swing.JTextField();
        lbVendedorSalBase = new javax.swing.JLabel();
        txtVendedorSalBase = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtVendedorTelefone1 = new javax.swing.JTextField();
        txtVendedorTaxaComissao = new javax.swing.JTextField();
        txtVendedorTelefone2 = new javax.swing.JTextField();
        cbxVendedorCPF = new javax.swing.JFormattedTextField();
        btnVendedorConsultar = new javax.swing.JButton();
        btnVendedorIncluir = new javax.swing.JButton();
        btnVendedorAlterar = new javax.swing.JButton();
        btnVendedorExcluir = new javax.swing.JButton();
        btnVendedorSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbVendedorCPF.setText("CPF");

        lbVendedorNome.setText("Nome");

        lbVendedorEnde.setText("Endereço");

        lbVendedorCidade.setText("Cidade");

        lbVendedorCEP.setText("CEP");

        txtVendedorNome.setEnabled(false);

        txtVendedorEndereco.setEnabled(false);

        txtVendedorCidade.setEnabled(false);

        txtVendedorCEP.setEnabled(false);

        lbVendedorSalBase.setText("Salário Base");

        txtVendedorSalBase.setEnabled(false);

        jLabel1.setText("UF");

        jLabel2.setText("Telefone");

        jLabel3.setText("Taxa Comissão");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setEnabled(false);

        txtVendedorTelefone1.setEnabled(false);

        txtVendedorTaxaComissao.setEnabled(false);
        txtVendedorTaxaComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendedorTaxaComissaoActionPerformed(evt);
            }
        });

        txtVendedorTelefone2.setEnabled(false);

        try {
            cbxVendedorCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnVendedorConsultar.setIcon(new javax.swing.ImageIcon("C:\\Users\\mumei\\Downloads\\DimasTrab-main\\prjPOOBrenoCaioJoao\\build\\classes\\icon\\pesq.png")); // NOI18N
        btnVendedorConsultar.setText("Consultar");

        btnVendedorIncluir.setIcon(new javax.swing.ImageIcon("C:\\Users\\mumei\\Downloads\\DimasTrab-main\\prjPOOBrenoCaioJoao\\build\\classes\\icon\\add.png")); // NOI18N
        btnVendedorIncluir.setText("Incluir");
        btnVendedorIncluir.setEnabled(false);

        btnVendedorAlterar.setIcon(new javax.swing.ImageIcon("C:\\Users\\mumei\\Downloads\\DimasTrab-main\\prjPOOBrenoCaioJoao\\build\\classes\\icon\\Alterar.png")); // NOI18N
        btnVendedorAlterar.setText("Alterar");
        btnVendedorAlterar.setEnabled(false);

        btnVendedorExcluir.setIcon(new javax.swing.ImageIcon("C:\\Users\\mumei\\Downloads\\DimasTrab-main\\prjPOOBrenoCaioJoao\\build\\classes\\icon\\Eraser.png")); // NOI18N
        btnVendedorExcluir.setText("Excluir");
        btnVendedorExcluir.setEnabled(false);

        btnVendedorSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\mumei\\Downloads\\DimasTrab-main\\prjPOOBrenoCaioJoao\\build\\classes\\icon\\exit.png")); // NOI18N
        btnVendedorSair.setText("Sair");
        btnVendedorSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedorSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbVendedorEnde)
                                            .addComponent(lbVendedorCidade)
                                            .addComponent(lbVendedorCEP))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtVendedorEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(txtVendedorCidade)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbVendedorNome)
                                            .addComponent(lbVendedorCPF))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtVendedorNome, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(cbxVendedorCPF))))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtVendedorCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbVendedorSalBase)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtVendedorSalBase, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtVendedorTelefone1))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVendedorTelefone2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtVendedorTaxaComissao)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVendedorConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVendedorIncluir)
                        .addGap(4, 4, 4)
                        .addComponent(btnVendedorAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVendedorExcluir)
                        .addGap(2, 2, 2)
                        .addComponent(btnVendedorSair, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedorCPF)
                    .addComponent(cbxVendedorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVendedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedorEnde)
                    .addComponent(txtVendedorEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedorCidade)
                    .addComponent(txtVendedorCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedorCEP)
                    .addComponent(txtVendedorCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtVendedorTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVendedorTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendedorSalBase)
                    .addComponent(txtVendedorSalBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtVendedorTaxaComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVendedorConsultar)
                    .addComponent(btnVendedorIncluir)
                    .addComponent(btnVendedorAlterar)
                    .addComponent(btnVendedorExcluir)
                    .addComponent(btnVendedorSair))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVendedorTaxaComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendedorTaxaComissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendedorTaxaComissaoActionPerformed

    private void btnVendedorSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedorSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnVendedorSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVendedorAlterar;
    private javax.swing.JButton btnVendedorConsultar;
    private javax.swing.JButton btnVendedorExcluir;
    private javax.swing.JButton btnVendedorIncluir;
    private javax.swing.JButton btnVendedorSair;
    private javax.swing.JFormattedTextField cbxVendedorCPF;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbVendedorCEP;
    private javax.swing.JLabel lbVendedorCPF;
    private javax.swing.JLabel lbVendedorCidade;
    private javax.swing.JLabel lbVendedorEnde;
    private javax.swing.JLabel lbVendedorNome;
    private javax.swing.JLabel lbVendedorSalBase;
    private javax.swing.JTextField txtVendedorCEP;
    private javax.swing.JTextField txtVendedorCidade;
    private javax.swing.JTextField txtVendedorEndereco;
    private javax.swing.JTextField txtVendedorNome;
    private javax.swing.JTextField txtVendedorSalBase;
    private javax.swing.JTextField txtVendedorTaxaComissao;
    private javax.swing.JTextField txtVendedorTelefone1;
    private javax.swing.JTextField txtVendedorTelefone2;
    // End of variables declaration//GEN-END:variables
}
